-- 创建帖子表

CREATE TABLE IF NOT EXISTS `post` (
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`author_id` INT UNSIGNED NOT NULL,
	`title` VARCHAR(20) NOT NULL,
	`content` TEXT NOT NULL,
	`pv` INT UNSIGNED DEFAULT 0,
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;